source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

# Disabling sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Flickr-Gallery' do

    # Pods for Flickr-Gallery iOS application
     
    pod 'MKProgress', '~> 1.0.9'       , :inhibit_warnings => true
    pod 'SnapKit', '~> 5.0'
    pod 'Alamofire', '~> 5.0.0-beta.5'

    # Pods for Flickr-GalleryTests Unit testing

    target 'Flickr-GalleryTests' do
        inherit! :search_paths
        pod 'Quick', '~> 2.1.0'
        pod 'Nimble', '~> 8.0.1'
        pod 'OHHTTPStubs/Swift', '~> 8.0.0'
    end
end
